# Generated by Django 5.1.1 on 2024-10-09 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='max_two_tickets_per_month',
        ),
    ]
